services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-nginx
    ports:
      - "8080:80"
    volumes:
      - ./Lab11:/var/www/html:rw
    depends_on:
      - php
    networks:
      - nginx_network

  php:
    build: 
      context: .
      dockerfile: ./php/Dockerfile
    container_name: web-php
    environment:
      APP_SALT: testSalt
    volumes:
      - ./Lab11:/var/www/html:rw
    networks:
      - nginx_network
  
  mysql:
    image: mysql
    container_name: web-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: blog
      TZ: Europe/Moscow
    networks:
      - nginx_network
    volumes:
      - ./data/db/volume:/var/lib/mysql
      - ./data/db/db.cnf:/etc/mysql/conf.d/my.cnf 

networks:
  nginx_network:
    driver: bridge
