services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-nginx
    ports:
      - "8080:80"
    volumes:
      - ./Lab7:/var/www/html:ro,Z
    depends_on:
      - php
    networks:
      - nginx_network

  php:
    image: php:fpm
    container_name: web-php
    volumes:
      - ./Lab7:/var/www/html:ro,Z
    networks:
      - nginx_network
  
  mysql:
    image: mysql
    container_name: web-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: blog
    volumes:
      - ./data/db/volume:/var/lib/mysql 

networks:
  nginx_network:
    driver: bridge
